name: ci

on:
  pull_request:
    branches: ['**']     # triggert auf alle Ziel-Branches
  workflow_dispatch:      # manueller Start im Actions-Tab

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Force Failure
        run: (exit 1)
