name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run tests (with coverage)
        run: go test -cover ./...

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Check formatting (fails if unformatted)
        # go fmt gibt geänderte Dateien auf stdout aus
        # test -z ... -> exit 0 wenn leer (alles formatiert), sonst 1
        run: test -z "$(go fmt ./...)"

